import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Astronaut from "@/components/molecules/Astronaut/Astronaut";

const Custom404: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dilshod | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/man.png" />
      </Head>
      <Astronaut />
    </>
  );
};

export default Custom404;
