import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Fallback404 from "@/components/templates/Fallback404/Fallback404";

const Custom404: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dilshod | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/man.png" />
      </Head>
      <Fallback404 />
    </>
  );
};

export default Custom404;
