import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "@/components/templates/Footer/Footer";
import Hero from "@/components/templates/Hero/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dilshod | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/man.png" />
      </Head>
      <Hero />
      <Footer />
      {/* <RecentPosts /> */}
      {/* <Footer /> */}
    </>
  );
};

export default Home;
