import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Hero from "@/components/templates/Hero/Hero";
import Footer from "@/components/templates/Footer/Footer";
import Header from "@/components/templates/Header/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dilshod | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/man.png" />
      </Head>
      <Header />
      <Hero />
      {/* Recent Posts */}
      <Footer />
    </>
  );
};

export default Home;
