import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/templates/Header/Header";
import Footer from "@/components/templates/Footer/Footer";
import Expertise from "@/components/templates/Expertise/Expertise";
import Divider from "@/components/atoms/Divider/Divider";
import Statistics from "@/components/templates/Statistics/Statistics";
import Delivery from "@/components/templates/Delivery/Delivery";
import Projects from "@/components/templates/Projects/Projects";
import Practices from "@/components/templates/Practices/Practices";

const Portfolio: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dilshod | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/man.png" />
      </Head>
      <Header />
      <div style={{ flex: "1 0 auto" }}>
        <Expertise />
        <Divider />
        <Statistics />
        <Divider />
        <Delivery />
        <Divider />
        <Projects />
        <Divider />
        <Practices />
      </div>
      <Footer />
    </>
  );
};

export default Portfolio;
